# .github/workflows/deploy.yml
name: Deploy React App to WordPress Theme

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checks out your repository so the workflow can access it
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      # Step 3: Install project dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the React app for production
      - name: Build React App
        run: npm run build

# Step 5: Setup SSH Agent
      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Step 6: Deploy with rsync
      - name: Deploy with rsync
        run: rsync -avz --delete dist/ your-server-user@your-server-ip:/var/www/html/wp-content/themes/twentytwentyfive/